@authUrl = https://1ukf62scg7.execute-api.eu-central-1.amazonaws.com/prod

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmZTYzMzdkMzU2ZDRjMDRmOWQ5YzMyYTVhZmE5ZWNmYTY2OWI2MjBhNjlmMmIwMmQ0ODdjNDNiNzJkZjVkMGUyIiwibmFtZSI6IkFsZXhhbmRlciBCZWhyZW5zIiwiaXNTdXBlckFkbWluIjp0cnVlLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EvQUFjSFR0ZkVqWVJQMFc0S01NWDlIMDljNkt0b2dpZ2R1bDNodGlVMkV1Nk89czk2LWMiLCJpYXQiOjE2ODU2MjEwMzksImV4cCI6MTY4NTYyMTkzOX0.5xX0j9tAbICiUAst_tXqj-AllOy2n63vdqlIRm7bboo

@userCookie = cafd77c1d447041f01bd4a747414ec2e1d5dc3821a4fb49630bc10669adfcddd

###

POST {{authUrl}}/tokens
Content-Type: application/json
Cookie: r_id={{userCookie}}

{
    "grant_type": "authorization_code"
}

###

GET {{authUrl}}/me
Content-Type: application/json
Cookie: r_id={{userCookie}}

###

POST {{authUrl}}/logout
Content-Type: application/json
Cookie: r_id={{userCookie}}

###

POST {{authUrl}}/clients
Content-Type: application/json

{
    "name": "Test Client"
}

###

POST {{authUrl}}/tokens
Content-Type: application/json

{
    "client_id": "01H7PK2NWXA32Z9D20J6K23Q8C",
    "client_secret": "d39447a54c152089004da41cc4e83c00bdbb6296fd317e8990e773f02a22281e",
    "grant_type": "client_credentials"
}