on:
    push:
        paths:
          - "auth-api-types/openapi.yaml"
        branches: main

jobs:
    publish-to-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: "18.x"
            - uses: pnpm/action-setup@v2
              with:
                version: 8.6.0
            - name: Install dependencies
              run: pnpm install
            - name: Build types and package
              run: pnpm run generate
              working-directory: auth-api-types
            - uses: JS-DevTools/npm-publish@v2
              with:
                token: ${{ secrets.NPM_TOKEN }}